// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Lury.Runner.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_ja {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_ja() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Lury.Runner.Resources.Language_ja", typeof(Language_ja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Program_Usage_Or {
            get {
                return ResourceManager.GetString("Program_Usage_Or", resourceCulture);
            }
        }
        
        internal static string Program_Cant_Open_File {
            get {
                return ResourceManager.GetString("Program_Cant_Open_File", resourceCulture);
            }
        }
        
        internal static string Program_Output_Info {
            get {
                return ResourceManager.GetString("Program_Output_Info", resourceCulture);
            }
        }
        
        internal static string Program_Output_Error {
            get {
                return ResourceManager.GetString("Program_Output_Error", resourceCulture);
            }
        }
        
        internal static string Program_Directory_Not_Found {
            get {
                return ResourceManager.GetString("Program_Directory_Not_Found", resourceCulture);
            }
        }
        
        internal static string Program_Usage {
            get {
                return ResourceManager.GetString("Program_Usage", resourceCulture);
            }
        }
        
        internal static string Program_Usage_Help {
            get {
                return ResourceManager.GetString("Program_Usage_Help", resourceCulture);
            }
        }
        
        internal static string Program_Compilation_Failed {
            get {
                return ResourceManager.GetString("Program_Compilation_Failed", resourceCulture);
            }
        }
        
        internal static string Program_Output_Warn {
            get {
                return ResourceManager.GetString("Program_Output_Warn", resourceCulture);
            }
        }
    }
}
