//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lury.Compiling.Logger.Resources.Message {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error_ja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error_ja() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lury.Compiling.Logger.Resources.Message.Error.ja-JP", typeof(Error_ja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   トークン化できない文字があります. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lexer_CannotTokenize {
            get {
                return ResourceManager.GetString("Lexer_CannotTokenize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なインデントがあります. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lexer_IllegalIndent {
            get {
                return ResourceManager.GetString("Lexer_IllegalIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シンタックスエラーです. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Parser_SyntaxError {
            get {
                return ResourceManager.GetString("Parser_SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル終端でのシンタックスエラーです. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Parser_SyntaxErrorAtEOF {
            get {
                return ResourceManager.GetString("Parser_SyntaxErrorAtEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期しないファイル終端です. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Parser_UnexpectedEOF {
            get {
                return ResourceManager.GetString("Parser_UnexpectedEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明なエラーです. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
